export const coursesData = [
  {
    id: 1,
    title: "Java Programming for Beginners",
    channel: "CodeAcademy",
    url: "https://www.youtube.com/watch?v=example1",
    duration: "2 hours 30 minutes",
    rating: 4.8,
    description: "Learn Java from scratch with this beginner-friendly course.",
    views: "1.2M",
    level: "Beginner",
    imageUrl: "https://via.placeholder.com/400x225?text=Java+Course"
  },
  {
    id: 2,
    title: "Master JavaScript in 30 Days",
    channel: "JavaScriptMastery",
    url: "https://www.youtube.com/watch?v=example2",
    duration: "3 hours",
    rating: 4.7,
    description: "A comprehensive guide to JavaScript, including ES6 features.",
    views: "850K",
    level: "Intermediate",
    imageUrl: "https://via.placeholder.com/400x225?text=JavaScript+Course"
  },
  {
    id: 3,
    title: "React for Beginners",
    channel: "ReactNerd",
    url: "https://www.youtube.com/watch?v=example3",
    duration: "4 hours",
    rating: 4.9,
    description: "Learn React from scratch, including hooks and context.",
    views: "1.5M",
    level: "Beginner",
    imageUrl: "https://via.placeholder.com/400x225?text=React+Course"
  },
  {
    id: 4,
    title: "CSS for Web Developers",
    channel: "DesignTutorials",
    url: "https://www.youtube.com/watch?v=example4",
    duration: "2 hours",
    rating: 4.6,
    description: "Master CSS from basic styling to advanced animations.",
    views: "600K",
    level: "Beginner to Advanced",
    imageUrl: "https://via.placeholder.com/400x225?text=CSS+Course"
  },
  {
    id: 5,
    title: "Python for Data Science",
    channel: "CodeWithHarry",
    url: "https://www.youtube.com/watch?v=example5",
    duration: "5 hours",
    rating: 4.8,
    description: "A comprehensive guide to using Python for data science and machine learning.",
    views: "1M",
    level: "Intermediate",
    imageUrl: "https://via.placeholder.com/400x225?text=Python+Course"
  },
  {
    id: 6,
    title: "Learn C Programming",
    channel: "TechMaster",
    url: "https://www.youtube.com/watch?v=example6",
    duration: "3 hours 30 minutes",
    rating: 4.7,
    description: "Master C programming, including pointers, memory management, and more.",
    views: "750K",
    level: "Intermediate",
    imageUrl: "https://via.placeholder.com/400x225?text=C+Course"
  },
  {
    id: 7,
    title: "C++ for Beginners",
    channel: "CPlusPlusAcademy",
    url: "https://www.youtube.com/watch?v=example7",
    duration: "4 hours",
    rating: 4.9,
    description: "Get started with C++ programming, object-oriented principles, and more.",
    views: "1.3M",
    level: "Beginner",
    imageUrl: "https://via.placeholder.com/400x225?text=C%2B%2B+Course"
  },
  {
    id: 8,
    title: "JavaScript for Advanced Developers",
    channel: "JavaScriptPro",
    url: "https://www.youtube.com/watch?v=example8",
    duration: "4 hours 15 minutes",
    rating: 4.8,
    description: "Advanced JavaScript topics including closures, promises, and async programming.",
    views: "900K",
    level: "Advanced",
    imageUrl: "https://via.placeholder.com/400x225?text=Advanced+JavaScript"
  },
  {
    id: 9,
    title: "Full-Stack Web Development with React and Node.js",
    channel: "WebDevMaster",
    url: "https://www.youtube.com/watch?v=example9",
    duration: "6 hours",
    rating: 4.9,
    description: "Build full-stack applications with React and Node.js from scratch.",
    views: "2M",
    level: "Advanced",
    imageUrl: "https://via.placeholder.com/400x225?text=Full-Stack+Course"
  },
  {
    id: 10,
    title: "Complete Guide to Machine Learning with Python",
    channel: "DataScienceMasters",
    url: "https://www.youtube.com/watch?v=example10",
    duration: "7 hours",
    rating: 4.9,
    description: "Learn the basics and advanced techniques of machine learning with Python.",
    views: "1.5M",
    level: "Advanced",
    imageUrl: "https://via.placeholder.com/400x225?text=Machine+Learning"
  },
  {
    id: 11,
    title: "Advanced React Patterns",
    channel: "ReactExperts",
    url: "https://www.youtube.com/watch?v=example11",
    duration: "3 hours 30 minutes",
    rating: 4.8,
    description: "Learn advanced React concepts like higher-order components, render props, and more.",
    views: "850K",
    level: "Advanced",
    imageUrl: "https://via.placeholder.com/400x225?text=Advanced+React"
  },
  {
    id: 12,
    title: "HTML & CSS for Beginners",
    channel: "WebDevBeginner",
    url: "https://www.youtube.com/watch?v=example12",
    duration: "1 hour 45 minutes",
    rating: 4.5,
    description: "A beginner-friendly course on HTML and CSS for building responsive websites.",
    views: "1M",
    level: "Beginner",
    imageUrl: "https://via.placeholder.com/400x225?text=HTML+CSS+Course"
  },
  {
    id: 13,
    title: "Node.js for Backend Development",
    channel: "NodeAcademy",
    url: "https://www.youtube.com/watch?v=example13",
    duration: "4 hours 15 minutes",
    rating: 4.7,
    description: "Learn backend development with Node.js, including Express and MongoDB.",
    views: "1.2M",
    level: "Intermediate",
    imageUrl: "https://via.placeholder.com/400x225?text=Node.js+Course"
  },
  {
    id: 14,
    title: "Swift for iOS Development",
    channel: "AppleDev",
    url: "https://www.youtube.com/watch?v=example14",
    duration: "5 hours",
    rating: 4.9,
    description: "Master iOS development with Swift, including UIKit and SwiftUI.",
    views: "1.5M",
    level: "Intermediate",
    imageUrl: "https://via.placeholder.com/400x225?text=Swift+Course"
  },
  {
    id: 15,
    title: "Introduction to Cybersecurity",
    channel: "CyberMastery",
    url: "https://www.youtube.com/watch?v=example15",
    duration: "4 hours",
    rating: 4.6,
    description: "Learn the basics of cybersecurity, ethical hacking, and online safety.",
    views: "1M",
    level: "Beginner",
    imageUrl: "https://via.placeholder.com/400x225?text=Cybersecurity+Course"
  }
];
